name:                tcc-magic
version:             0.4.0.0
github:              "githubuser/prototipo2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/prototipo2#readme>

dependencies:
- base >= 4.7 && < 5
- text
- mtl
- operational
- optics
- optics-th
- template-haskell
- fused-effects == 1.1.*
- fused-effects-optics
- ilist
- multiset
- enummapset
- containers

library:
  source-dirs: src

executables:
  tcc-magic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tcc-magic

tests:
  tcc-magic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tcc-magic
